### ISSUE TITLE
Access to script at 'https://unpkg.com/dimport?module' from origin '' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by Naragod** [lukeed/dimport#10]
I received the following issue today. Why is CORS suddenly being implemented? Is an issue with the server hosting dimport being down? 
![Server Error](https://user-images.githubusercontent.com/7035353/60224478-8fdde380-9850-11e9-9d1a-e583a5be9d96.PNG)

**Comment by lukeed** [comment]
It's `unpkg.com` – they've been having weird issues lately. I see this all the time too with a whole bunch of modules.

My best guess is that it's their GCP Function waking up for the first time in a while and dropping the request, either due to timeout or an error in the handler 🤷‍♂ 

Because unpkg is on CloudFlare, any 500-level error is perceived as a CORS error in most/all browsers.

Either way, this isnt a `dimport` issue. Just an unfortunate & impacted "usage" option that's out of my control.

**Comment by Naragod** [comment]
Thanks for explaining.
